import {useEffect,useState} from "react";
import {branches,commitRevision,createBranch,createProject,eventSocket,getJob,login,projects,register,revisionHistory,setToken,submitJob} from "./api";
import type {Branch,Job,Mode,Project,Revision,User} from "./types";
const modes:Mode[]=["Math","Team","Debug","Build","Review"];
export default function App(){
 const [user,setUser]=useState<User|null>(null),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[isRegister,setIsRegister]=useState(false);
 const [projectList,setProjectList]=useState<Project[]>([]),[project,setProject]=useState<Project|null>(null),[branchList,setBranchList]=useState<Branch[]>([]),[branch,setBranch]=useState<Branch|null>(null);
 const [mode,setMode]=useState<Mode>("Math"),[projectName,setProjectName]=useState(""),[description,setDescription]=useState(""),[message,setMessage]=useState("Initial mathematics revision"),[docText,setDocText]=useState('{"expression":"x^2 + 2*x + 1"}'),[branchName,setBranchName]=useState("feature/new-branch"),[history,setHistory]=useState<Revision[]>([]);
 const [a,setA]=useState("12"),[b,setB]=useState("30"),[operation,setOperation]=useState("add"),[job,setJob]=useState<Job|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function refreshProjects(){const p=await projects();setProjectList(p);if(!project&&p[0])setProject(p[0]);}
 async function authenticate(e:React.FormEvent){e.preventDefault();setError("");try{const r=isRegister?await register(email,password):await login(email,password);setUser(r.user);await refreshProjects();}catch(err){setError(err instanceof Error?err.message:"Authentication failed");}}
 useEffect(()=>{if(!user||!project)return;branches(project.id).then(list=>{setBranchList(list);setBranch(list[0]??null)}).catch(e=>setError(String(e)));},[user,project?.id]);
 useEffect(()=>{if(!user||!project)return;const close=eventSocket(project.id,event=>{setNotice("Live collaboration event received");console.info("AxiomForge event",event)});return close;},[user,project?.id]);
 useEffect(()=>{if(!user||!project||!branch)return;revisionHistory(project.id,branch.id).then(setHistory).catch(e=>setError(String(e)));},[user,project?.id,branch?.id,branch?.head_revision_id]);
 async function makeProject(e:React.FormEvent){e.preventDefault();try{const r=await createProject(projectName,description);setProject(r.project);setBranch(r.defaultBranch);setBranchList([r.defaultBranch]);setProjectList(await projects());setProjectName("");setDescription("");setNotice("Project created");}catch(e){setError(String(e));}}
 async function makeBranch(e:React.FormEvent){e.preventDefault();if(!project)return;try{const r=await createBranch(project.id,branchName);setBranchList([...branchList,r.branch]);setBranch(r.branch);setBranchName("");setNotice("Branch created");setError("");}catch(e){setError(String(e));}}
 async function saveRevision(){if(!project||!branch)return;try{const document=JSON.parse(docText) as Record<string,unknown>;const r=await commitRevision(project.id,branch.id,message,document,branch.head_revision_id);setBranch({...branch,head_revision_id:r.revision.id});setBranchList(branchList.map(b=>b.id===branch.id?{...b,head_revision_id:r.revision.id}:b));setNotice("Revision committed: "+r.revision.id);setError("");}catch(e){setError(String(e));}}
 async function runMath(){if(!project)return;try{const r=await submitJob(project.id,operation,Number(a),operation==="prime"?undefined:Number(b));setJob(r.job);setNotice("Job queued");setTimeout(async()=>{try{const updated=await getJob(r.job.id);setJob(updated.job)}catch{}},1200);}catch(e){setError(String(e));}}
 function logout(){setToken(null);setUser(null);setProject(null);setProjectList([]);setBranch(null);setBranchList([]);}
 if(!user)return <main className="auth"><div className="brand-mark">AX</div><p className="eyebrow">MATHEMATICAL DEVELOPMENT PLATFORM</p><h1>AxiomForge</h1><p className="muted">Model mathematics. Collaborate on proofs. Build with confidence.</p><form onSubmit={authenticate} className="panel auth-panel"><h2>{isRegister?"Create your account":"Welcome back"}</h2><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" minLength={12} required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary">{isRegister?"Create account":"Sign in"}</button><button type="button" className="link" onClick={()=>setIsRegister(!isRegister)}>{isRegister?"Already have an account? Sign in":"New here? Create an account"}</button>{error&&<p className="error">{error}</p>}</form><small>Development client · API v1</small></main>;
 return <div className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark small">AX</span><strong>AxiomForge</strong><span className="tag">DEV 0.1</span></div><div className="top-actions"><span className="muted">{user.email}</span><button className="secondary" onClick={logout}>Sign out</button></div></header>
 <div className="modebar">{modes.map(m=><button key={m} className={mode===m?"mode active":"mode"} onClick={()=>setMode(m)}>{m}</button>)}</div>
 <div className="workspace"><aside className="sidebar"><div className="side-heading">PROJECTS <span>{projectList.length}</span></div>{projectList.map(p=><button key={p.id} className={project?.id===p.id?"project-item selected":"project-item"} onClick={()=>setProject(p)}><span className="project-dot"/><span><b>{p.name}</b><small>{p.role}</small></span></button>)}<form onSubmit={makeProject} className="new-project"><input placeholder="Project name" value={projectName} onChange={e=>setProjectName(e.target.value)} required/><input placeholder="Description (optional)" value={description} onChange={e=>setDescription(e.target.value)}/><button className="secondary">+ New project</button></form><div className="sidebar-footer"><span className="status-dot"/> API workspace</div></aside>
 <main className="main-panel"><div className="breadcrumb"><span>Workspace</span><span>/</span><strong>{project?.name??"Select a project"}</strong><span className="spacer"/><span className="branch-label">Branch</span><select value={branch?.id??""} onChange={e=>setBranch(branchList.find(x=>x.id===e.target.value)??null)}><option value="">No branch</option>{branchList.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select><form className="branch-create" onSubmit={makeBranch}><input aria-label="New branch name" placeholder="new branch" value={branchName} onChange={e=>setBranchName(e.target.value)} required/><button className="secondary">+ Branch</button></form></div>
 {!project?<section className="empty"><div className="empty-icon">∑</div><h2>Your mathematics workspace</h2><p>Create a project to begin working with equations, revisions, and team collaboration.</p></section>:<>
 <div className="page-title"><div><p className="eyebrow">{mode.toUpperCase()} MODE</p><h1>{mode==="Math"?"Mathematics workspace":mode==="Team"?"Team collaboration":mode==="Debug"?"Debug & inspect":mode==="Build"?"Build & jobs":"Review & release"}</h1><p className="muted">{project.description||"A shared workspace for mathematical artifacts."}</p></div><span className="role-chip">{project.role}</span></div>
 {mode==="Math"&&<div className="content-grid"><section className="panel editor"><div className="panel-head"><div><h2>Mathematical document</h2><p>JSON document snapshot · revision controlled</p></div><span className="live-pill">LOCAL EDITOR</span></div><textarea className="code-editor" spellCheck={false} value={docText} onChange={e=>setDocText(e.target.value)}/><div className="commit-row"><input aria-label="Revision message" value={message} onChange={e=>setMessage(e.target.value)}/><button className="primary" onClick={saveRevision} disabled={!branch}>Commit revision</button></div></section><section className="panel calculator"><div className="panel-head"><div><h2>Quick computation</h2><p>Queue a bounded math job</p></div><span className="math-icon">ƒx</span></div><label>Operation<select value={operation} onChange={e=>setOperation(e.target.value)}><option value="add">Addition</option><option value="subtract">Subtraction</option><option value="multiply">Multiplication</option><option value="divide">Division</option><option value="prime">Primality</option></select></label><div className="number-row"><label>Input A<input value={a} onChange={e=>setA(e.target.value)} inputMode="decimal"/></label>{operation!=="prime"&&<label>Input B<input value={b} onChange={e=>setB(e.target.value)} inputMode="decimal"/></label>}</div><button className="primary full" onClick={runMath}>Run computation →</button>{job&&<div className="job-result"><span className="muted">JOB {job.id.slice(0,8)}</span><strong className={"job-status "+job.status}>{job.status}</strong><pre>{JSON.stringify(job.output??job.error??{queued:true},null,2)}</pre></div>}</section></div>}
 {mode==="Team"&&<section className="panel"><h2>Team & permissions</h2><p className="muted">Role-based access is enforced by the API. Use project membership endpoints to invite existing accounts and assign editor, reviewer, or viewer roles.</p><div className="info-row"><span>Current user</span><b>{user.email}</b></div><div className="info-row"><span>Your project role</span><b>{project.role}</b></div><div className="info-row"><span>Collaboration transport</span><b>WebSocket · API v1</b></div></section>}
 {mode==="Debug"&&<section className="panel"><h2>Revision diagnostics</h2><div className="info-row"><span>Project ID</span><code>{project.id}</code></div><div className="info-row"><span>Branch ID</span><code>{branch?.id??"—"}</code></div><div className="info-row"><span>Head revision</span><code>{branch?.head_revision_id??"No commits yet"}</code></div><div className="info-row"><span>Document JSON</span><b>{(()=>{try{JSON.parse(docText);return "Valid JSON"}catch{return "Invalid JSON"}})()}</b></div><h2 className="history-heading">Recent revisions</h2>{history.length?history.slice(0,10).map(r=><div className="history-item" key={r.id}><b>{r.message}</b><small>{new Date(r.created_at).toLocaleString()}</small><code>{r.id.slice(0,12)}</code></div>):<p className="muted">No revisions committed to this branch yet.</p>}</section>}
 {mode==="Build"&&<section className="panel"><h2>Build & job queue</h2><p className="muted">Math evaluation runs in the development worker. Arbitrary code and build scripts are not executed by this worker.</p>{job?<div className="info-row"><span>{job.kind}</span><b className={"job-status "+job.status}>{job.status}</b></div>:<p>No jobs submitted in this session. Use Mathematics mode to queue a computation.</p>}</section>}
 {mode==="Review"&&<section className="panel"><h2>Review & release</h2><p className="muted">Review and release API endpoints are available; this UI panel is a navigation placeholder pending the full revision-diff interface.</p><div className="info-row"><span>Current branch</span><b>{branch?.name??"—"}</b></div><div className="info-row"><span>Latest head</span><code>{branch?.head_revision_id??"No revisions"}</code></div></section>}
 </>}
 {notice&&<div className="toast" role="status">{notice}<button onClick={()=>setNotice("")}>×</button></div>}{error&&<div className="toast error-toast" role="alert">{error}<button onClick={()=>setError("")}>×</button></div>}
 </main></div></div>;
}
