import fs from "node:fs";
import http from "node:http";
import https from "node:https";
import express from "express";
import cors from "cors";
import helmet from "helmet";
import {config} from "./config";
import {healthRouter} from "./routes/health";
import {authRouter} from "./routes/auth";
import {projectsRouter} from "./routes/projects";
import {revisionsRouter} from "./routes/revisions";
import {jobsRouter} from "./routes/jobs";
import {errorHandler,notFound} from "./middleware/errors";
import {attachWebSockets} from "./websocket";
const app=express();
app.disable("x-powered-by");app.use(helmet());app.use(cors({origin:config.CORS_ORIGIN.split(",").map(v=>v.trim()),credentials:false}));app.use(express.json({limit:"1mb"}));
app.use("/api/v1/health",healthRouter);app.use("/api/v1/auth",authRouter);app.use("/api/v1/projects",projectsRouter);app.use("/api/v1/revisions",revisionsRouter);app.use("/api/v1/jobs",jobsRouter);app.use(notFound);app.use(errorHandler);
const server=(config.TLS_KEY_PATH&&config.TLS_CERT_PATH)?https.createServer({key:fs.readFileSync(config.TLS_KEY_PATH),cert:fs.readFileSync(config.TLS_CERT_PATH)},app):http.createServer(app);
attachWebSockets(server);
server.listen(config.PORT,()=>console.log(`AxiomForge API listening on port ${config.PORT} (${config.NODE_ENV})`));
const shutdown=()=>server.close(()=>process.exit(0));process.on("SIGTERM",shutdown);process.on("SIGINT",shutdown);
