#include "axiomforge/core/graph.hpp"
#include <algorithm>
#include <queue>
#include <unordered_set>
namespace axf {
bool KnowledgeGraph::add_node(Node n){return nodes_.emplace(n.id,std::move(n)).second;}
bool KnowledgeGraph::add_edge(Edge e){if(!nodes_.contains(e.from)||!nodes_.contains(e.to))return false;edges_.push_back(std::move(e));return true;}
const Node* KnowledgeGraph::find(const std::string& id)const{auto i=nodes_.find(id);return i==nodes_.end()?nullptr:&i->second;}
std::vector<Node> KnowledgeGraph::children(const std::string& id)const{std::vector<Node> out;for(const auto&e:edges_)if(e.from==id&&e.relation=="contains")if(auto*n=find(e.to))out.push_back(*n);std::sort(out.begin(),out.end(),[](const Node&a,const Node&b){return a.id<b.id;});return out;}
std::vector<std::string> KnowledgeGraph::path(const std::string&a,const std::string&b)const{if(!find(a)||!find(b))return{};std::queue<std::string>q;q.push(a);std::unordered_set<std::string>seen{a};std::unordered_map<std::string,std::string>parent;while(!q.empty()){auto u=q.front();q.pop();if(u==b)break;for(const auto&e:edges_)if(e.from==u&&!seen.contains(e.to)){seen.insert(e.to);parent[e.to]=u;q.push(e.to);}}if(!seen.contains(b))return{};std::vector<std::string>out;for(auto cur=b;;cur=parent[cur]){out.push_back(cur);if(cur==a)break;}std::reverse(out.begin(),out.end());return out;}
std::vector<Node> KnowledgeGraph::all_nodes()const{std::vector<Node>out;for(const auto&[_,n]:nodes_)out.push_back(n);std::sort(out.begin(),out.end(),[](const Node&a,const Node&b){return a.id<b.id;});return out;}
KnowledgeGraph make_default_graph(){KnowledgeGraph g;auto n=[&](const char*i,const char*name,NodeType t){g.add_node({i,name,t,{},{}});};auto e=[&](const char*a,const char*r,const char*b){g.add_edge({a,r,b});};n("mathematics","Mathematics",NodeType::Root);const char* bs[]={"foundations","number_systems","arithmetic","number_theory","algebra","geometry","trigonometry","calculus","differential_equations","linear_algebra","probability","statistics","discrete_math","analysis","topology","abstract_algebra","transforms","optimization","numerical_math","information_theory","computation","mathematical_physics"};for(auto b:bs){n(b,b,NodeType::Branch);e("mathematics","contains",b);}n("logic","Logic",NodeType::SubBranch);n("set_theory","Set Theory",NodeType::SubBranch);n("limits","Limits",NodeType::SubBranch);n("derivatives","Derivatives",NodeType::SubBranch);n("integrals","Integrals",NodeType::SubBranch);n("prime_numbers","Prime Numbers",NodeType::SubBranch);e("foundations","contains","logic");e("foundations","contains","set_theory");e("calculus","contains","limits");e("calculus","contains","derivatives");e("calculus","contains","integrals");e("number_theory","contains","prime_numbers");e("calculus","depends_on","algebra");e("differential_equations","depends_on","calculus");return g;}
}
